- hosts: all
  vars_files:
    - vars/user_vars.yaml
  tasks:
    - name: Create user {{ username }}
      user:
        name: "{{ username }}"
        comment: "{{ first_name }} {{ last_name }}"
        shell: "{{ shell }}"
        home: "{{ home }}"
