- name: "Package management"
  hosts: all
  tasks:
    - name: "Ensure base packages are present"
      yum:
        name: "{{ item }}"
        state: latest
      loop:
        - git
        - vim
        - bind-utils
        - python-setuptools
