- name: "Package management"
  hosts: all
  vars: 
    base_packages:
      - git
      - vim
      - bind-utils
      - python-setuptools
  tasks:
    - name: "Ensure base packages are present"
      yum:
        name: "{{ item }}"
        state: latest
      with_items: "{{ base_packages }}"
