---
- hosts: all
  become: false
  vars:
  tasks:
    - name: Create and empty image file
      command: dd if=/dev/zero of=/tmp/test.img bs=1M count=1000
      async: 1
      poll: 0
      register: result
      ignore_errors: true
    - name: Print debug info
      debug:
        var: result
    - name: Check job results
      async_status:
        jid: "{{ result.ansible_job_id }}"
      register: dd_job
      until: dd_job.finished
      retries: 30
      delay: 5
