---
- hosts: webservers
  remote_user: devops
  become: true
  serial: 1
  vars:
    web_svc: httpd
  tasks:
    - name: Disable {{ inventory_hostname }} web server in the app lb pool
      haproxy:
        state: disabled
        host: "{{ inventory_hostname }}"
        backend: app
        socket: /var/lib/haproxy/stats
        wait: yes
      delegate_to: "{{ item }}"
      with_items: "{{ groups['lbserver'] }}"

    - name: Deploy new version of index.html
      template:
        src: index-ver1.html.j2
        dest: /var/www/html/index.html
      register: pageupgrade

    - name: Service is restarted
      service: 
        name: "{{ web_svc }}"
        state: restarted
      when: pageupgrade.changed

    - name: Wait for httpd service to come up
      wait_for:
        port: 80
        host: "{{ inventory_hostname }}"
        timeout: 20
      when: pageupgrade.changed

    - name: Enable {{ inventory_hostname }} web server in the app lb pool
      haproxy:
        state: enabled
        host: "{{ inventory_hostname }}"
        backend: app
        socket: /var/lib/haproxy/stats
        wait: yes
      delegate_to: "{{ item }}"
      with_items: "{{ groups['lbserver'] }}"
