---
- hosts: www1.example.com
  become: true
  remote_user: ansible
  vars:
    pkg: httpd
    svc: httpd
  tasks:
    - name: "{{ pkg }} is installed"
      yum:
        name: "{{ pkg }}"
        state: latest
    - name: "{{ svc }} is started"
      service:
        name: "{{ svc }}"
        state: started
    - name: Add content
      copy:
        content: "A simple web page\n"
        dest: /var/www/html/index.html
        owner: apache
        group: apache
        mode: 0644
    - name: Test functionality
      become: false
      uri:
        url: http://www1.example.com
        status_code: 200
      delegate_to: localhost
