---
- name: "A simple play"
  hosts: webservers
  tasks:
    - name: "Package httpd is installed"
      yum:
        name: httpd
        state: latest

    - name: "Service httpd is started and enabled"
      service:
        name: httpd
        state: started
        enabled: true

