---
- name: User creation 
  hosts: localhost
  vars:
    user_name: john
    user_pwd: changeme
    user_shell: /bin/bash
    user_groups: wheel
  tasks:
    - name: Ensure user {{ user_name }} is created
      user: 
        name: "{{ user_name }}"
        password: "{{ user_pwd | password_hash('sha512') }}"
        shell: "{{ user_shell }}"
        groups: "{{ user_groups }}"
        append: true
      
 
